# =============================================================================
# Project       : IoT-Based Intelligent Building Decision Support System
# Notebook      : 01 - Data Understanding
# Author        : Srihari Mudakavi
#
# Description:
# This notebook performs the initial exploration of the primary IoT dataset.
# It verifies that the dataset has been loaded correctly and provides
# descriptive information required for the Capstone Project Synopsis.
# =============================================================================


# =============================================================================
# SECTION 1 : IMPORT REQUIRED LIBRARIES
# =============================================================================
#
# Import the libraries required for data manipulation and numerical analysis.
# These libraries will be used throughout the project for data exploration,
# preprocessing, statistical analysis, and machine learning.
# =============================================================================

import pandas as pd
import numpy as np


# =============================================================================
# SECTION 2 : CONFIGURE DISPLAY SETTINGS
# =============================================================================
#
# Configure pandas display options to improve readability while exploring
# the dataset.
# =============================================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

print("Libraries imported successfully.")

In [2]:
# =============================================================================
# Project       : IoT-Based Intelligent Building Decision Support System
# Notebook      : 01 - Data Understanding
# Author        : Srihari Mudakavi
#
# Description:
# This notebook performs the initial exploration of the primary IoT dataset.
# It verifies that the dataset has been loaded correctly and provides
# descriptive information required for the Capstone Project Synopsis.
# =============================================================================


# =============================================================================
# SECTION 1 : IMPORT REQUIRED LIBRARIES
# =============================================================================
#
# Import the libraries required for data manipulation and numerical analysis.
# These libraries will be used throughout the project for data exploration,
# preprocessing, statistical analysis, and machine learning.
# =============================================================================

import pandas as pd
import numpy as np


# =============================================================================
# SECTION 2 : CONFIGURE DISPLAY SETTINGS
# =============================================================================
#
# Configure pandas display options to improve readability while exploring
# the dataset.
# =============================================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# =============================================================================
# SECTION 3 : IMPORT PATH LIBRARY
# =============================================================================
#
# The pathlib library provides an operating system independent approach for
# handling file and directory paths. It improves code readability and ensures
# compatibility across different platforms.
# =============================================================================

from pathlib import Path


# =============================================================================
# SECTION 4 : DEFINE PROJECT DIRECTORY STRUCTURE
# =============================================================================
#
# Define the project root directory and the locations of the datasets.
# Using Path objects makes the project easier to maintain and reproduce.
# =============================================================================

# Project Root Directory
PROJECT_ROOT = Path.cwd().parent

# Data Directory
DATA_DIRECTORY = PROJECT_ROOT / "data" / "raw"

# Dataset Directories
IBLEND_DIRECTORY = DATA_DIRECTORY / "i_blend"
NASA_DIRECTORY = DATA_DIRECTORY / "nasa_power"
SMART_BUILDING_DIRECTORY = DATA_DIRECTORY / "smart_building_2025"

print("Project directories configured successfully.")
print(f"Project Root : {PROJECT_ROOT}")

Project directories configured successfully.
Project Root : c:\Users\User\OneDrive\Documents\IoT-Based-Intelligent-Building-DSS

In [4]:
# =============================================================================
# SECTION 5 : VERIFY I-BLEND DATASET AVAILABILITY
# =============================================================================
#
# This section verifies that the primary I-BLEND dataset exists before
# attempting to load it. Performing this validation helps prevent file
# loading errors and improves the reproducibility of the project.
# =============================================================================

# Define the primary dataset file
IBLEND_FILE = IBLEND_DIRECTORY / "all_buildings_power.csv"

# Verify dataset availability
if IBLEND_FILE.exists():
    print("✅ I-BLEND dataset located successfully.")
    print(f"Dataset Path:\n{IBLEND_FILE}")
else:
    print("❌ Dataset not found.")
    print("Please verify that 'all_buildings_power.csv' is available in:")
    print(IBLEND_DIRECTORY)

✅ I-BLEND dataset located successfully.
Dataset Path:
c:\Users\User\OneDrive\Documents\IoT-Based-Intelligent-Building-DSS\data\raw\i_blend\all_buildings_power.csv

In [5]:
# =============================================================================
# SECTION 6 : LOAD THE PRIMARY I-BLEND DATASET
# =============================================================================
#
# This section loads the primary I-BLEND dataset into a pandas DataFrame.
# The dataset contains IoT-based building power measurements that will serve
# as the primary data source for exploratory analysis and subsequent machine
# learning tasks.
#
# Exception handling is included to ensure that any file loading issues are
# reported clearly.
# =============================================================================

try:
    # Load the dataset
    energy_df = pd.read_csv(IBLEND_FILE)

    print("=" * 70)
    print("PRIMARY DATASET LOADED SUCCESSFULLY")
    print("=" * 70)
    print(f"Dataset Name      : {IBLEND_FILE.name}")
    print(f"Number of Rows    : {energy_df.shape[0]:,}")
    print(f"Number of Columns : {energy_df.shape[1]}")
    print("=" * 70)

except Exception as error:
    print("=" * 70)
    print("ERROR LOADING DATASET")
    print("=" * 70)
    print(error)

======================================================================
PRIMARY DATASET LOADED SUCCESSFULLY
======================================================================
Dataset Name      : all_buildings_power.csv
Number of Rows    : 2,310,568
Number of Columns : 10
======================================================================

In [6]:
# =============================================================================
# SECTION 7 : DATASET PREVIEW
# =============================================================================
#
# Display the first five observations from the primary dataset. This provides
# an initial understanding of the dataset structure, available variables,
# and sample records before performing further analysis.
#
# This output will also be used as a screenshot in the Capstone Project
# Synopsis.
# =============================================================================

print("=" * 70)
print("PRIMARY DATASET PREVIEW")
print("=" * 70)

display(energy_df.head())

======================================================================
PRIMARY DATASET PREVIEW
======================================================================

,timestamp,Academic,Boys_main,Boys_backup,Facilities,Girls_main,Girls_backup,Lecture,Library,Mess
0,1.376073e+09,28368.60645,28298.05859,11521.14258,NaN,9817.66846,6324.17847,0.0,3972.19702,NaN
1,1.376073e+09,28411.98828,28327.11426,11532.83105,NaN,9804.43408,6348.66260,0.0,3972.83789,NaN
2,1.376073e+09,28752.53809,28343.01562,11538.75635,NaN,9834.51758,6384.14258,0.0,3974.43042,NaN
3,1.376073e+09,29031.44629,28447.11719,11879.18115,NaN,9881.32666,6404.63501,0.0,3981.96484,NaN
4,1.376073e+09,28487.45801,28393.62207,12565.78662,NaN,9894.75684,6434.62622,0.0,3986.44995,NaN

In [7]:
# =============================================================================
# SECTION 8 : DATASET DIMENSIONS
# =============================================================================
#
# This section displays the dimensions of the primary dataset.
# Understanding the number of observations and variables provides an
# overview of the dataset size before performing further analysis.
#
# This output will also be included in the Capstone Project Synopsis.
# =============================================================================

print("=" * 70)
print("PRIMARY DATASET DIMENSIONS")
print("=" * 70)

number_of_rows = energy_df.shape[0]
number_of_columns = energy_df.shape[1]

print(f"Total Number of Records  : {number_of_rows:,}")
print(f"Total Number of Features : {number_of_columns}")

print("=" * 70)

======================================================================
PRIMARY DATASET DIMENSIONS
======================================================================
Total Number of Records  : 2,310,568
Total Number of Features : 10
======================================================================

In [8]:
# =============================================================================
# SECTION 9 : DATASET STRUCTURE AND DATA TYPES
# =============================================================================
#
# This section provides comprehensive information about the primary
# I-BLEND dataset. It displays the number of observations, feature names,
# data types, memory usage, and non-null value counts for each variable.
#
# Understanding the dataset structure is essential before performing
# preprocessing, feature engineering, and statistical analysis.
# =============================================================================

print("=" * 80)
print("DATASET STRUCTURE")
print("=" * 80)

energy_df.info()

print("=" * 80)

================================================================================
DATASET STRUCTURE
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2310568 entries, 0 to 2310567
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     float64
 1   Academic      float64
 2   Boys_main     float64
 3   Boys_backup   float64
 4   Facilities    float64
 5   Girls_main    float64
 6   Girls_backup  float64
 7   Lecture       float64
 8   Library       float64
 9   Mess          float64
dtypes: float64(10)
memory usage: 176.3 MB
================================================================================

In [9]:
# =============================================================================
# SECTION 10 : DESCRIPTIVE STATISTICAL SUMMARY
# =============================================================================
#
# Generate descriptive statistics for all numerical features contained in
# the primary I-BLEND dataset. These statistics provide an overview of the
# data distribution and support the initial data understanding phase of
# the research.
# =============================================================================

print("=" * 80)
print("DESCRIPTIVE STATISTICAL SUMMARY")
print("=" * 80)

descriptive_statistics = energy_df.describe().transpose()

display(descriptive_statistics)

print("=" * 80)
print(f"Number of Features Analysed : {descriptive_statistics.shape[0]}")
print("=" * 80)

================================================================================
DESCRIPTIVE STATISTICAL SUMMARY
================================================================================

,count,mean,std,min,25%,50%,75%,max
timestamp,2310568.0,1.445394e+09,4.002673e+07,1.376073e+09,1.410732e+09,1.445390e+09,1.480049e+09,1.514745e+09
Academic,2269527.0,2.778582e+04,1.401836e+04,0.000000e+00,1.813406e+04,2.334184e+04,3.324996e+04,9.578633e+04
Boys_main,1671544.0,1.748801e+04,8.375309e+03,0.000000e+00,1.151557e+04,1.559360e+04,2.150550e+04,9.766386e+04
Boys_backup,1688043.0,1.392737e+04,5.152703e+03,0.000000e+00,1.001611e+04,1.306873e+04,1.729778e+04,4.721214e+04
Facilities,2048903.0,1.045892e+04,4.673187e+03,0.000000e+00,8.073814e+03,9.860552e+03,1.230265e+04,1.394371e+05
Girls_main,1653053.0,7.315914e+03,2.658483e+03,0.000000e+00,5.314344e+03,7.079641e+03,8.994355e+03,2.089592e+04
Girls_backup,2300745.0,6.881255e+03,2.116446e+03,0.000000e+00,5.312342e+03,6.782574e+03,8.319595e+03,1.812682e+04
Lecture,2269309.0,6.416937e+02,1.552832e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.670307e+04
Library,1713637.0,9.074730e+03,6.655733e+03,0.000000e+00,4.483057e+03,6.710730e+03,1.153799e+04,9.920895e+04
Mess,2013089.0,2.219535e+04,8.822726e+03,2.324592e+02,1.556387e+04,2.064835e+04,2.734457e+04,1.424421e+05

================================================================================
Number of Features Analysed : 10
================================================================================

In [10]:
# =============================================================================
# SECTION 11 : MISSING VALUE ANALYSIS
# =============================================================================
#
# This section evaluates the completeness of the primary I-BLEND dataset by
# identifying missing values in each feature. Understanding missing data is
# essential before applying preprocessing techniques such as imputation or
# feature selection.
#
# =============================================================================

print("=" * 80)
print("MISSING VALUE ANALYSIS")
print("=" * 80)

missing_value_summary = pd.DataFrame({
    "Missing Values": energy_df.isnull().sum(),
    "Percentage (%)": round((energy_df.isnull().sum() / len(energy_df)) * 100, 2)
})

display(missing_value_summary)

print("=" * 80)
print(f"Features with Missing Values : {(missing_value_summary['Missing Values'] > 0).sum()}")
print("=" * 80)

================================================================================
MISSING VALUE ANALYSIS
================================================================================

              Missing Values  Percentage (%)
timestamp                  0            0.00
Academic               41041            1.78
Boys_main             639024           27.66
Boys_backup           622525           26.94
Facilities            261665           11.32
Girls_main            657515           28.46
Girls_backup            9823            0.43
Lecture                41259            1.79
Library               596931           25.83
Mess                  297479           12.87

================================================================================
Features with Missing Values : 9
================================================================================

In [11]:
# =============================================================================
# SECTION 12 : FEATURE INFORMATION SUMMARY
# =============================================================================
#
# This section summarises the characteristics of each feature including the
# data type, number of non-null observations, missing values, and percentage
# completeness. The summary assists in planning subsequent preprocessing
# activities.
#
# =============================================================================

feature_information = pd.DataFrame({
    "Data Type": energy_df.dtypes,
    "Non-Null Count": energy_df.count(),
    "Missing Values": energy_df.isnull().sum(),
    "Completeness (%)": round((energy_df.count() / len(energy_df)) * 100, 2)
})

print("=" * 80)
print("FEATURE INFORMATION SUMMARY")
print("=" * 80)

display(feature_information)

================================================================================
FEATURE INFORMATION SUMMARY
================================================================================

             Data Type  Non-Null Count  Missing Values  Completeness (%)
timestamp      float64         2310568               0            100.00
Academic       float64         2269527           41041             98.22
Boys_main      float64         1671544          639024             72.34
Boys_backup    float64         1688043          622525             73.06
Facilities     float64         2048903          261665             88.68
Girls_main     float64         1653053          657515             71.54
Girls_backup   float64         2300745            9823             99.57
Lecture        float64         2269309           41259             98.21
Library        float64         1713637          596931             74.17
Mess           float64         2013089          297479             87.13

In [12]:
# =============================================================================
# SECTION 13 : INITIAL DATASET OBSERVATIONS
# =============================================================================
#
# This section provides a high-level summary of the primary dataset based on
# the exploratory analysis conducted in the previous sections. These
# observations will guide the preprocessing and feature engineering phases.
#
# =============================================================================

print("=" * 80)
print("INITIAL DATASET OBSERVATIONS")
print("=" * 80)

print(f"Total Records               : {energy_df.shape[0]:,}")
print(f"Total Features              : {energy_df.shape[1]}")

print(f"Numerical Features          : {energy_df.select_dtypes(include=['number']).shape[1]}")
print(f"Categorical Features        : {energy_df.select_dtypes(include=['object']).shape[1]}")

print(f"Features Containing Missing Values : {(energy_df.isnull().sum() > 0).sum()}")

print("=" * 80)

================================================================================
INITIAL DATASET OBSERVATIONS
================================================================================
Total Records               : 2,310,568
Total Features              : 10
Numerical Features          : 10
Categorical Features        : 0
Features Containing Missing Values : 9
================================================================================

In [13]:
# =============================================================================
# SECTION 14 : NOTEBOOK CONCLUSION
# =============================================================================
#
# The primary I-BLEND dataset has been successfully identified, validated,
# and explored. Initial assessment confirms that the dataset is suitable
# for subsequent preprocessing and machine learning tasks.
#
# The next notebook will focus on data preprocessing, including handling
# missing values, timestamp conversion, duplicate detection, and data
# quality improvement.
#
# =============================================================================

print("=" * 80)
print("DATA UNDERSTANDING COMPLETED SUCCESSFULLY")
print("=" * 80)

print("""
Completed Activities
--------------------
✓ Dataset successfully located
✓ Dataset loaded successfully
✓ Dataset preview generated
✓ Dataset dimensions analysed
✓ Dataset structure examined
✓ Descriptive statistics generated
✓ Missing value analysis completed
✓ Feature information summarised

Next Notebook
-------------
02_Data_Preprocessing.ipynb

Status
------
Ready for Data Preprocessing
""")

print("=" * 80)

================================================================================
DATA UNDERSTANDING COMPLETED SUCCESSFULLY
================================================================================

Completed Activities
--------------------
✓ Dataset successfully located
✓ Dataset loaded successfully
✓ Dataset preview generated
✓ Dataset dimensions analysed
✓ Dataset structure examined
✓ Descriptive statistics generated
✓ Missing value analysis completed
✓ Feature information summarised

Next Notebook
-------------
02_Data_Preprocessing.ipynb

Status
------
Ready for Data Preprocessing

================================================================================

In [14]:
# =============================================================================
# SECTION 15 : LOAD NASA POWER DATASET
# =============================================================================

NASA_FILE = NASA_DIRECTORY / "nasapower.csv"

nasa_df = pd.read_csv(
    NASA_FILE,
    skiprows=11
)

print("=" * 80)
print("NASA POWER DATASET LOADED SUCCESSFULLY")
print("=" * 80)
print(f"Dataset Name      : {NASA_FILE.name}")
print(f"Number of Rows    : {nasa_df.shape[0]:,}")
print(f"Number of Columns : {nasa_df.shape[1]}")
print("=" * 80)

================================================================================
NASA POWER DATASET LOADED SUCCESSFULLY
================================================================================
Dataset Name      : nasapower.csv
Number of Rows    : 1,605
Number of Columns : 6
================================================================================

In [15]:
display(nasa_df.head())

   YEAR  MO  DY  ALLSKY_SFC_SW_DWN  WS2M  PRECTOTCORR
0  2013   8  10             217.51  1.11         5.21
1  2013   8  11             177.33  1.69         0.93
2  2013   8  12             203.67  1.56         1.44
3  2013   8  13             198.01  2.04         1.93
4  2013   8  14             212.87  2.16        11.13

In [16]:
nasa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1605 entries, 0 to 1604
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   YEAR               1605 non-null   int64
 1   MO                 1605 non-null   int64
 2   DY                 1605 non-null   int64
 3   ALLSKY_SFC_SW_DWN  1605 non-null   float64
 4   WS2M               1605 non-null   float64
 5   PRECTOTCORR        1605 non-null   float64
dtypes: float64(3), int64(3)
memory usage: 75.4 KB

In [17]:
nasa_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
YEAR,1605.0,2015.276012,1.284069,2013.00,2014.00,2015.00,2016.00,2017.00
MO,1605.0,6.846106,3.472998,1.00,4.00,7.00,10.00,12.00
DY,1605.0,15.796885,8.791850,1.00,8.00,16.00,23.00,31.00
ALLSKY_SFC_SW_DWN,1605.0,200.697003,64.884944,20.75,151.10,200.38,253.32,350.10
WS2M,1605.0,1.841601,0.758321,0.48,1.28,1.72,2.26,5.72
PRECTOTCORR,1605.0,1.967427,6.045617,0.00,0.00,0.00,0.66,88.39

In [18]:
nasa_df.isnull().sum()

YEAR                 0
MO                   0
DY                   0
ALLSKY_SFC_SW_DWN    0
WS2M                 0
PRECTOTCORR          0
dtype: int64

In [19]:
# =============================================================================
# SECTION 20 : LOAD SMART BUILDING DATASETS
# =============================================================================
#
# This section loads the Smart Building 2025 datasets. These datasets are
# used for external validation and comparative analysis of the proposed
# Intelligent Building Decision Support System.
# =============================================================================

SMART_BUILDING_DIRECTORY = PROJECT_ROOT / "data" / "raw" / "smart_building_2025"

# Load datasets
electricity_df = pd.read_csv(
    SMART_BUILDING_DIRECTORY / "electricity_P.csv"
)

weather_df = pd.read_csv(
    SMART_BUILDING_DIRECTORY / "weather.csv"
)

cooling_df = pd.read_csv(
    SMART_BUILDING_DIRECTORY / "cooling_P.csv"
)

heating_df = pd.read_csv(
    SMART_BUILDING_DIRECTORY / "heating_P.csv"
)

print("=" * 80)
print("SMART BUILDING DATASETS LOADED SUCCESSFULLY")
print("=" * 80)

print(f"Electricity Dataset : {electricity_df.shape}")
print(f"Weather Dataset     : {weather_df.shape}")
print(f"Cooling Dataset     : {cooling_df.shape}")
print(f"Heating Dataset     : {heating_df.shape}")

print("=" * 80)

================================================================================
SMART BUILDING DATASETS LOADED SUCCESSFULLY
================================================================================
Electricity Dataset : (52584, 4)
Weather Dataset     : (52608, 3)
Cooling Dataset     : (52584, 3)
Heating Dataset     : (52584, 4)
================================================================================

In [20]:
# =============================================================================
# SECTION 22 : SMART BUILDING DATASET STRUCTURE
# =============================================================================

datasets = {
    "Electricity": electricity_df,
    "Weather": weather_df,
    "Cooling": cooling_df,
    "Heating": heating_df
}

for dataset_name, dataset in datasets.items():

    print("\n" + "=" * 90)
    print(f"{dataset_name.upper()} DATASET")
    print("=" * 90)

    print("\nColumns:")
    print(list(dataset.columns))

    print("\nData Types:")
    print(dataset.dtypes)

    print("\nMissing Values:")
    print(dataset.isnull().sum())

    print("\nFirst Five Rows:")
    display(dataset.head())

==========================================================================================
ELECTRICITY DATASET
==========================================================================================

Columns:
['datetime_utc', 'total', 'PV', 'CHP']

Data Types:
datetime_utc     object
total           float64
PV              float64
CHP             float64
dtype: object

Missing Values:
datetime_utc        0
total               0
PV              13055
CHP                 0
dtype: int64

First Five Rows:

          datetime_utc         total  PV            CHP
0  2017-12-31 23:00:00  48119.801926 NaN -141611.518667
1  2018-01-01 00:00:00  73709.255599 NaN -116945.953833
2  2018-01-01 01:00:00   3523.699562 NaN -185698.193167
3  2018-01-01 02:00:00  47272.888623 NaN -144207.283500
4  2018-01-01 03:00:00  24441.443153 NaN -164294.822000

==========================================================================================
WEATHER DATASET
==========================================================================================

Columns:
['datetime_utc', 'WeatherStation.Weather.Igm', 'WeatherStation.Weather.Ta']

Data Types:
datetime_utc                   object
WeatherStation.Weather.Igm    float64
WeatherStation.Weather.Ta     float64
dtype: object

Missing Values:
datetime_utc                     0
WeatherStation.Weather.Igm    1234
WeatherStation.Weather.Ta     1234
dtype: int64

First Five Rows:

          datetime_utc  WeatherStation.Weather.Igm  WeatherStation.Weather.Ta
0  2017-12-30 23:00:00                    0.064194                  11.129424
1  2017-12-31 00:00:00                    0.000000                  10.986136
2  2017-12-31 01:00:00                    0.000000                  10.688404
3  2017-12-31 02:00:00                    0.000000                  11.146773
4  2017-12-31 03:00:00                    0.037363                  12.163473

==========================================================================================
COOLING DATASET
==========================================================================================

Columns:
['datetime_utc', 'total', 'cool_elec']

Data Types:
datetime_utc     object
total           float64
cool_elec       float64
dtype: object

Missing Values:
datetime_utc    0
total           0
cool_elec       0
dtype: int64

First Five Rows:

          datetime_utc       total    cool_elec
0  2017-12-31 23:00:00  688.793103  1213.917583
1  2018-01-01 00:00:00  661.666667  1196.451917
2  2018-01-01 01:00:00  628.333333  1228.437833
3  2018-01-01 02:00:00  620.833333  1211.249167
4  2018-01-01 03:00:00  622.500000  1217.024500

==========================================================================================
HEATING DATASET
==========================================================================================

Columns:
['datetime_utc', 'total', 'CHP_heat', 'CHP_elec']

Data Types:
datetime_utc     object
total           float64
CHP_heat        float64
CHP_elec        float64
dtype: object

Missing Values:
datetime_utc    0
total           0
CHP_heat        0
CHP_elec        0
dtype: int64

First Five Rows:

          datetime_utc          total       CHP_heat       CHP_elec
0  2017-12-31 23:00:00  330053.333333  211263.333333 -141611.518667
1  2018-01-01 00:00:00  322531.666667  196696.666667 -116945.953833
2  2018-01-01 01:00:00  396676.666667  279819.666667 -185698.193167
3  2018-01-01 02:00:00  359306.666667  238123.500000 -144207.283500
4  2018-01-01 03:00:00  389196.666667  246002.250000 -164294.822000

In [21]:
# =============================================================================
# SECTION 23 : DATA INTEGRATION PREPARATION
# =============================================================================
#
# Objective
# ---------
# Prepare the three research datasets for integration by converting their
# respective date and time representations into a common datetime format.
#
# The three datasets have different temporal resolutions:
#
#   • I-BLEND          → Minute-level observations
#   • NASA POWER       → Daily observations
#   • Smart Building   → Hourly observations
#
# A common datetime representation is therefore required before performing
# temporal alignment and feature integration.
#
# =============================================================================

print("=" * 90)
print("DATA INTEGRATION PREPARATION")
print("=" * 90)

print("Converting timestamp columns into datetime format...\n")

==========================================================================================
DATA INTEGRATION PREPARATION
==========================================================================================
Converting timestamp columns into datetime format...

In [22]:
# =============================================================================
# SECTION 24 : CONVERT I-BLEND UNIX TIMESTAMP
# =============================================================================
#
# The I-BLEND dataset stores timestamps in UNIX Epoch format.
# Convert these values into Python datetime objects and derive useful
# temporal attributes for later merging and feature engineering.
#
# =============================================================================

energy_df["datetime"] = pd.to_datetime(
    energy_df["timestamp"],
    unit="s"
)

energy_df["date"] = energy_df["datetime"].dt.date
energy_df["year"] = energy_df["datetime"].dt.year
energy_df["month"] = energy_df["datetime"].dt.month
energy_df["day"] = energy_df["datetime"].dt.day
energy_df["hour"] = energy_df["datetime"].dt.hour

print("=" * 90)
print("I-BLEND TIMESTAMP CONVERTED SUCCESSFULLY")
print("=" * 90)

display(
    energy_df[
        [
            "timestamp",
            "datetime",
            "date",
            "year",
            "month",
            "day",
            "hour"
        ]
    ].head()
)

==========================================================================================
I-BLEND TIMESTAMP CONVERTED SUCCESSFULLY
==========================================================================================

      timestamp            datetime        date  year  month  day  hour
0  1.376073e+09 2013-08-09 18:30:00  2013-08-09  2013      8    9    18
1  1.376073e+09 2013-08-09 18:31:00  2013-08-09  2013      8    9    18
2  1.376073e+09 2013-08-09 18:32:00  2013-08-09  2013      8    9    18
3  1.376073e+09 2013-08-09 18:33:00  2013-08-09  2013      8    9    18
4  1.376073e+09 2013-08-09 18:34:00  2013-08-09  2013      8    9    18

In [23]:
# =============================================================================
# SECTION 25 : CONVERT NASA DATE COLUMNS
# =============================================================================
#
# NASA POWER stores YEAR, MONTH and DAY as separate variables.
# Combine these variables into a single datetime column.
#
# =============================================================================

nasa_df["date"] = pd.to_datetime(
    nasa_df[
        ["YEAR", "MO", "DY"]
    ].rename(
        columns={
            "YEAR": "year",
            "MO": "month",
            "DY": "day"
        }
    )
)

nasa_df["date"] = nasa_df["date"].dt.date

print("=" * 90)
print("NASA DATE CREATED SUCCESSFULLY")
print("=" * 90)

display(
    nasa_df.head()
)

==========================================================================================
NASA DATE CREATED SUCCESSFULLY
==========================================================================================

   YEAR  MO  DY  ALLSKY_SFC_SW_DWN  WS2M  PRECTOTCORR        date
0  2013   8  10             217.51  1.11         5.21  2013-08-10
1  2013   8  11             177.33  1.69         0.93  2013-08-11
2  2013   8  12             203.67  1.56         1.44  2013-08-12
3  2013   8  13             198.01  2.04         1.93  2013-08-13
4  2013   8  14             212.87  2.16        11.13  2013-08-14

In [24]:
# =============================================================================
# SECTION 26 : CONVERT SMART BUILDING DATETIME
# =============================================================================
#
# Convert all Smart Building timestamps into datetime format.
# These timestamps will later be used for external validation.
#
# =============================================================================

datasets = {
    "Electricity": electricity_df,
    "Weather": weather_df,
    "Cooling": cooling_df,
    "Heating": heating_df
}

for dataset_name, dataset in datasets.items():

    dataset["datetime"] = pd.to_datetime(
        dataset["datetime_utc"]
    )

    dataset["date"] = dataset["datetime"].dt.date
    dataset["year"] = dataset["datetime"].dt.year
    dataset["month"] = dataset["datetime"].dt.month
    dataset["day"] = dataset["datetime"].dt.day
    dataset["hour"] = dataset["datetime"].dt.hour

print("=" * 90)
print("SMART BUILDING TIMESTAMPS CONVERTED SUCCESSFULLY")
print("=" * 90)

==========================================================================================
SMART BUILDING TIMESTAMPS CONVERTED SUCCESSFULLY
==========================================================================================

In [25]:
# =============================================================================
# SECTION 27 : VERIFY TEMPORAL ALIGNMENT
# =============================================================================
#
# Compare the temporal coverage of all datasets before integration.
#
# =============================================================================

summary = pd.DataFrame({

    "Dataset":[
        "I-BLEND",
        "NASA POWER",
        "Smart Building Electricity"
    ],

    "Start Date":[
        energy_df["datetime"].min(),
        nasa_df["date"].min(),
        electricity_df["datetime"].min()
    ],

    "End Date":[
        energy_df["datetime"].max(),
        nasa_df["date"].max(),
        electricity_df["datetime"].max()
    ]

})

print("=" * 90)
print("TEMPORAL COVERAGE")
print("=" * 90)

display(summary)

==========================================================================================
TEMPORAL COVERAGE
==========================================================================================

                      Dataset           Start Date             End Date
0                     I-BLEND  2013-08-09 18:30:00  2017-12-31 18:29:00
1                  NASA POWER           2013-08-10           2017-12-31
2  Smart Building Electricity  2017-12-31 23:00:00  2023-12-31 22:00:00

In [26]:
# =============================================================================
# SECTION 28 : TEMPORAL RESOLUTION ANALYSIS
# =============================================================================
#
# Determine the sampling frequency of the I-BLEND dataset and verify whether
# daily aggregation is required before merging with the NASA POWER dataset.
# =============================================================================

print("=" * 100)
print("TEMPORAL RESOLUTION ANALYSIS")
print("=" * 100)

print("I-BLEND")
print(f"Minimum Timestamp : {energy_df['datetime'].min()}")
print(f"Maximum Timestamp : {energy_df['datetime'].max()}")

print("\nTotal Records")
print(len(energy_df))

print("\nUnique Dates")
print(energy_df["date"].nunique())

print("\nAverage Records Per Day")
print(round(len(energy_df) / energy_df["date"].nunique(), 2))

print("=" * 100)

====================================================================================================
TEMPORAL RESOLUTION ANALYSIS
====================================================================================================
I-BLEND
Minimum Timestamp : 2013-08-09 18:30:00
Maximum Timestamp : 2017-12-31 18:29:00

Total Records
2310568

Unique Dates
1606

Average Records Per Day
1438.71
====================================================================================================

In [27]:
# =============================================================================
# SECTION 29 : INTEGRATE I-BLEND AND NASA POWER DATASETS
# =============================================================================
#
# Objective
# ---------
# Integrate the primary IoT building energy dataset (I-BLEND) with the NASA
# POWER environmental dataset using the common calendar date.
#
# Integration Key
# ---------------
# date
#
# Environmental Variables Added
# -----------------------------
# • ALLSKY_SFC_SW_DWN  : Solar Radiation
# • WS2M               : Wind Speed (2 m)
# • PRECTOTCORR        : Corrected Precipitation
#
# =============================================================================

# Select only the required NASA variables
nasa_features = nasa_df[
    [
        "date",
        "ALLSKY_SFC_SW_DWN",
        "WS2M",
        "PRECTOTCORR"
    ]
].copy()

# Perform left join to preserve every I-BLEND observation
integrated_df = energy_df.merge(
    nasa_features,
    how="left",
    on="date"
)

print("=" * 100)
print("DATASET INTEGRATION COMPLETED SUCCESSFULLY")
print("=" * 100)

print(f"I-BLEND Records        : {len(energy_df):,}")
print(f"NASA POWER Records     : {len(nasa_df):,}")
print(f"Integrated Records     : {len(integrated_df):,}")

print("=" * 100)

====================================================================================================
DATASET INTEGRATION COMPLETED SUCCESSFULLY
====================================================================================================
I-BLEND Records        : 2,310,568
NASA POWER Records     : 1,605
Integrated Records     : 2,310,568
====================================================================================================

In [28]:
# =============================================================================
# SECTION 30 : VERIFY DATASET INTEGRATION
# =============================================================================

print("=" * 100)
print("POST-INTEGRATION VALIDATION")
print("=" * 100)

print("\nIntegrated Dataset Shape")
print(integrated_df.shape)

print("\nNew Environmental Variables")

new_columns = [
    "ALLSKY_SFC_SW_DWN",
    "WS2M",
    "PRECTOTCORR"
]

print(integrated_df[new_columns].head())

print("\nMissing Values After Integration")

display(
    integrated_df[new_columns].isnull().sum()
)

print("=" * 100)

====================================================================================================
POST-INTEGRATION VALIDATION
====================================================================================================

Integrated Dataset Shape
(2310568, 19)

New Environmental Variables
   ALLSKY_SFC_SW_DWN  WS2M  PRECTOTCORR
0                NaN   NaN          NaN
1                NaN   NaN          NaN
2                NaN   NaN          NaN
3                NaN   NaN          NaN
4                NaN   NaN          NaN

Missing Values After Integration

ALLSKY_SFC_SW_DWN    330
WS2M                 330
PRECTOTCORR          330
dtype: int64

====================================================================================================

In [29]:
# =============================================================================
# SECTION 31 : DATASET INTEGRITY VALIDATION
# =============================================================================
#
# Objective
# ---------
# Verify that the dataset integration process has preserved the integrity
# of the original I-BLEND dataset while successfully enriching it with
# NASA POWER environmental variables.
#
# =============================================================================

print("=" * 100)
print("DATASET INTEGRITY VALIDATION")
print("=" * 100)

print(f"Original I-BLEND Records      : {len(energy_df):,}")
print(f"Integrated Dataset Records    : {len(integrated_df):,}")

print()

print("Duplicate Records")
print(integrated_df.duplicated().sum())

print()

print("Duplicate Date-Time Records")
print(integrated_df.duplicated(subset=["datetime"]).sum())

print()

print("Number of Features")
print(integrated_df.shape[1])

print("=" * 100)

====================================================================================================
DATASET INTEGRITY VALIDATION
====================================================================================================
Original I-BLEND Records      : 2,310,568
Integrated Dataset Records    : 2,310,568

Duplicate Records
0

Duplicate Date-Time Records
0

Number of Features
19
====================================================================================================

In [30]:
# =============================================================================
# SECTION 32 : SAVE INTEGRATED DATASET
# =============================================================================

OUTPUT_DIRECTORY = PROJECT_ROOT / "data" / "processed"

OUTPUT_DIRECTORY.mkdir(exist_ok=True)

OUTPUT_FILE = OUTPUT_DIRECTORY / "integrated_building_dataset.csv"

integrated_df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("=" * 100)
print("INTEGRATED DATASET SAVED SUCCESSFULLY")
print("=" * 100)

print(f"Location : {OUTPUT_FILE}")

====================================================================================================
INTEGRATED DATASET SAVED SUCCESSFULLY
====================================================================================================
Location : c:\Users\User\OneDrive\Documents\IoT-Based-Intelligent-Building-DSS\data\processed\integrated_building_dataset.csv

In [31]:
# =============================================================================
# SECTION 33 : MERGE SMART BUILDING DATASETS
# =============================================================================
#
# Objective
# ---------
# Combine the Smart Building electricity, weather, cooling, and heating
# datasets into a single unified dataset using the common timestamp.
#
# This unified dataset will be used for external validation of the
# proposed Intelligent Building Decision Support System.
#
# =============================================================================

# Merge Electricity and Weather
smart_building_df = electricity_df.merge(
    weather_df,
    on="datetime_utc",
    how="outer"
)

# Merge Cooling
smart_building_df = smart_building_df.merge(
    cooling_df,
    on="datetime_utc",
    how="outer",
    suffixes=("", "_cooling")
)

# Merge Heating
smart_building_df = smart_building_df.merge(
    heating_df,
    on="datetime_utc",
    how="outer",
    suffixes=("", "_heating")
)

print("=" * 100)
print("SMART BUILDING DATASETS MERGED SUCCESSFULLY")
print("=" * 100)

print(f"Rows    : {smart_building_df.shape[0]:,}")
print(f"Columns : {smart_building_df.shape[1]}")

display(smart_building_df.head())

====================================================================================================
SMART BUILDING DATASETS MERGED SUCCESSFULLY
====================================================================================================
Rows    : 52,608
Columns : 35

,datetime_utc,total,PV,CHP,datetime_x,date_x,year_x,month_x,day_x,hour_x,WeatherStation.Weather.Igm,WeatherStation.Weather.Ta,datetime_y,date_y,year_y,month_y,day_y,hour_y,total_cooling,cool_elec,datetime,date,year,month,day,hour,total_heating,CHP_heat,CHP_elec,datetime_heating,date_heating,year_heating,month_heating,day_heating,hour_heating
0,2017-12-30 23:00:00,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.064194,11.129424,2017-12-30 23:00:00,2017-12-30,2017,12,30,23,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,2017-12-31 00:00:00,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.000000,10.986136,2017-12-31 00:00:00,2017-12-31,2017,12,31,0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,2017-12-31 01:00:00,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.000000,10.688404,2017-12-31 01:00:00,2017-12-31,2017,12,31,1,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3,2017-12-31 02:00:00,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.000000,11.146773,2017-12-31 02:00:00,2017-12-31,2017,12,31,2,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
4,2017-12-31 03:00:00,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,0.037363,12.163473,2017-12-31 03:00:00,2017-12-31,2017,12,31,3,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [32]:
# =============================================================================
# SECTION 34 : VALIDATE SMART BUILDING DATASET
# =============================================================================

print("=" * 100)
print("SMART BUILDING DATASET VALIDATION")
print("=" * 100)

print(f"Shape : {smart_building_df.shape}")

print("\nMissing Values")
display(smart_building_df.isnull().sum())

print("\nDuplicate Records")
print(smart_building_df.duplicated().sum())

print("\nColumn Names")
print(list(smart_building_df.columns))

====================================================================================================
SMART BUILDING DATASET VALIDATION
====================================================================================================
Shape : (52608, 35)

Missing Values

datetime_utc         0
total               24
PV               13079
CHP                 24
datetime_x          24
                 ...
date_heating        24
year_heating        24
month_heating       24
day_heating         24
hour_heating        24
Length: 35, dtype: int64

Duplicate Records
0

Column Names
['datetime_utc', 'total', 'PV', 'CHP', 'datetime_x', 'date_x', 'year_x', 'month_x', 'day_x', 'hour_x', 'WeatherStation.Weather.Igm', 'WeatherStation.Weather.Ta', 'datetime_y', 'date_y', 'year_y', 'month_y', 'day_y', 'hour_y', 'total_cooling', 'cool_elec', 'datetime', 'date', 'year', 'month', 'day', 'hour', 'total_heating', 'CHP_heat', 'CHP_elec', 'datetime_heating', 'date_heating', 'year_heating', 'month_heating', 'day_heating', 'hour_heating']

In [33]:
# =============================================================================
# SECTION 35 : CREATE CLEAN SMART BUILDING VALIDATION DATASET
# =============================================================================
#
# Objective
# ---------
# Create a clean validation dataset by removing duplicate temporal columns
# generated during dataset merging and assigning meaningful feature names.
#
# =============================================================================

smart_validation_df = smart_building_df.copy()

# Remove duplicate temporal columns
columns_to_drop = [
    "datetime_x", "date_x", "year_x", "month_x", "day_x", "hour_x",
    "datetime_y", "date_y", "year_y", "month_y", "day_y", "hour_y",
    "datetime_heating", "date_heating", "year_heating",
    "month_heating", "day_heating", "hour_heating"
]

smart_validation_df.drop(
    columns=columns_to_drop,
    inplace=True,
    errors="ignore"
)

# Rename columns for clarity
smart_validation_df.rename(columns={
    "total": "electricity_total",
    "WeatherStation.Weather.Igm": "solar_irradiance",
    "WeatherStation.Weather.Ta": "air_temperature"
}, inplace=True)

print("=" * 100)
print("CLEAN SMART BUILDING VALIDATION DATASET CREATED")
print("=" * 100)

print(f"Rows    : {smart_validation_df.shape[0]:,}")
print(f"Columns : {smart_validation_df.shape[1]}")

print("\nColumns:")
print(list(smart_validation_df.columns))

====================================================================================================
CLEAN SMART BUILDING VALIDATION DATASET CREATED
====================================================================================================
Rows    : 52,608
Columns : 17

Columns:
['datetime_utc', 'electricity_total', 'PV', 'CHP', 'solar_irradiance', 'air_temperature', 'total_cooling', 'cool_elec', 'datetime', 'date', 'year', 'month', 'day', 'hour', 'total_heating', 'CHP_heat', 'CHP_elec']

In [34]:
# =============================================================================
# SECTION 36 : SAVE SMART BUILDING VALIDATION DATASET
# =============================================================================

VALIDATION_FILE = OUTPUT_DIRECTORY / "smart_building_validation_dataset.csv"

smart_validation_df.to_csv(
    VALIDATION_FILE,
    index=False
)

print("=" * 100)
print("SMART BUILDING VALIDATION DATASET SAVED")
print("=" * 100)

print(f"Location : {VALIDATION_FILE}")

====================================================================================================
SMART BUILDING VALIDATION DATASET SAVED
====================================================================================================
Location : c:\Users\User\OneDrive\Documents\IoT-Based-Intelligent-Building-DSS\data\processed\smart_building_validation_dataset.csv

In [36]:
# Load integrated dataset
df = integrated_df

# Shape
print("Dataset Shape:", df.shape)

# Missing values
missing = df.isnull().sum()

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": (missing / len(df)) * 100
})

print("\nMissing Value Summary:\n")
print(missing_df)

# Show only columns with missing values
print("\nColumns Having Missing Values:\n")
print(missing_df[missing_df["Missing Values"] > 0])

Dataset Shape: (2310568, 19)

Missing Value Summary:

                   Missing Values  Percentage
timestamp                       0    0.000000
Academic                    41041    1.776230
Boys_main                  639024   27.656576
Boys_backup                622525   26.942509
Facilities                 261665   11.324705
Girls_main                 657515   28.456856
Girls_backup                 9823    0.425134
Lecture                     41259    1.785665
Library                    596931   25.834816
Mess                       297479   12.874713
datetime                        0    0.000000
date                            0    0.000000
year                            0    0.000000
month                           0    0.000000
day                             0    0.000000
hour                            0    0.000000
ALLSKY_SFC_SW_DWN             330    0.014282
WS2M                          330    0.014282
PRECTOTCORR                   330    0.014282

Columns Having Missing Values:

                   Missing Values  Percentage
Academic                    41041    1.776230
Boys_main                  639024   27.656576
Boys_backup                622525   26.942509
Facilities                 261665   11.324705
Girls_main                 657515   28.456856
Girls_backup                 9823    0.425134
Lecture                     41259    1.785665
Library                    596931   25.834816
Mess                       297479   12.874713
ALLSKY_SFC_SW_DWN             330    0.014282
WS2M                          330    0.014282
PRECTOTCORR                   330    0.014282

In [37]:
# Missing values by percentage
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)

print(missing_percent)

Girls_main           28.456856
Boys_main            27.656576
Boys_backup          26.942509
Library              25.834816
Mess                 12.874713
Facilities           11.324705
Lecture               1.785665
Academic              1.776230
Girls_backup          0.425134
ALLSKY_SFC_SW_DWN     0.014282
WS2M                  0.014282
PRECTOTCORR           0.014282
timestamp             0.000000
datetime              0.000000
date                  0.000000
day                   0.000000
month                 0.000000
year                  0.000000
hour                  0.000000
dtype: float64

In [38]:
weather_cols = [
    "ALLSKY_SFC_SW_DWN",
    "WS2M",
    "PRECTOTCORR"
]

df = df.dropna(subset=weather_cols)

print(df.shape)

(2310238, 19)

In [39]:
print("="*60)
print("Weather Missing Values")
print("="*60)

print(df[weather_cols].isnull().sum())

============================================================
Weather Missing Values
============================================================
ALLSKY_SFC_SW_DWN    0
WS2M                 0
PRECTOTCORR          0
dtype: int64

In [41]:
df.to_csv(
    r"C:\Users\User\OneDrive\Documents\IoT-Based-Intelligent-Building-DSS\data\processed\integrated_building_dataset.csv",
    index=False
)

print("="*60)
print("CLEANED INTEGRATED DATASET SAVED SUCCESSFULLY")
print("="*60)
print("Rows :", len(df))
print("Columns :", len(df.columns))

============================================================
CLEANED INTEGRATED DATASET SAVED SUCCESSFULLY
============================================================
Rows : 2310238
Columns : 19

In [42]:
building_cols = [
    "Academic",
    "Boys_main",
    "Boys_backup",
    "Facilities",
    "Girls_main",
    "Girls_backup",
    "Lecture",
    "Library",
    "Mess"
]

for col in building_cols:
    print("="*60)
    print(col)
    print("First non-null :", df[col].first_valid_index())
    print("Last non-null  :", df[col].last_valid_index())

============================================================
Academic
First non-null : 330
Last non-null  : 2310567
============================================================
Boys_main
First non-null : 330
Last non-null  : 2310567
============================================================
Boys_backup
First non-null : 330
Last non-null  : 2310567
============================================================
Facilities
First non-null : 139680
Last non-null  : 2310567
============================================================
Girls_main
First non-null : 330
Last non-null  : 2310567
============================================================
Girls_backup
First non-null : 330
Last non-null  : 2310567
============================================================
Lecture
First non-null : 330
Last non-null  : 2310567
============================================================
Library
First non-null : 330
Last non-null  : 2310567
============================================================
Mess
First non-null : 64800
Last non-null  : 2310567

In [43]:
building_cols = [
    "Academic",
    "Boys_main",
    "Boys_backup",
    "Facilities",
    "Girls_main",
    "Girls_backup",
    "Lecture",
    "Library",
    "Mess"
]

for col in building_cols:
    print("=" * 60)
    print(col)

    temp = df[df[col].isnull()][["datetime"]]

    if len(temp) > 0:
        print("First Missing :", temp.iloc[0]["datetime"])
        print("Last Missing  :", temp.iloc[-1]["datetime"])
        print("Total Missing :", len(temp))
    else:
        print("No Missing Values")

============================================================
Academic
First Missing : 2013-08-28 08:37:00
Last Missing  : 2017-12-16 10:14:00
Total Missing : 41041
============================================================
Boys_main
First Missing : 2013-08-14 09:36:00
Last Missing  : 2017-11-23 10:07:00
Total Missing : 639024
============================================================
Boys_backup
First Missing : 2013-08-14 09:36:00
Last Missing  : 2017-10-25 04:50:00
Total Missing : 622525
============================================================
Facilities
First Missing : 2013-08-10 00:00:00
Last Missing  : 2017-12-16 10:13:00
Total Missing : 261335
============================================================
Girls_main
First Missing : 2013-08-16 12:32:00
Last Missing  : 2017-11-17 02:55:00
Total Missing : 657515
============================================================
Girls_backup
First Missing : 2013-08-17 10:37:00
Last Missing  : 2017-11-09 15:10:00
Total Missing : 9823
============================================================
Lecture
First Missing : 2013-08-10 01:01:00
Last Missing  : 2017-12-16 10:14:00
Total Missing : 41259
============================================================
Library
First Missing : 2013-09-04 23:41:00
Last Missing  : 2017-12-16 10:13:00
Total Missing : 596931
============================================================
Mess
First Missing : 2013-08-10 00:00:00
Last Missing  : 2017-12-29 08:14:00
Total Missing : 297149

In [44]:
import pandas as pd

# Convert datetime to datetime type
df["datetime"] = pd.to_datetime(df["datetime"])

# Sort by time
df = df.sort_values("datetime")

# Set datetime as index
df = df.set_index("datetime")

building_cols = [
    "Academic",
    "Boys_main",
    "Boys_backup",
    "Facilities",
    "Girls_main",
    "Girls_backup",
    "Lecture",
    "Library",
    "Mess"
]

# Time-based interpolation
df[building_cols] = df[building_cols].interpolate(method="time")

C:\Users\User\AppData\Local\Temp\ipykernel_19384\359044024.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["datetime"] = pd.to_datetime(df["datetime"])

In [45]:
df[building_cols] = df[building_cols].ffill().bfill()

In [46]:
df = df.reset_index()

In [47]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

print(missing)

                   Missing Values  Percentage
datetime                        0         0.0
timestamp                       0         0.0
Academic                        0         0.0
Boys_main                       0         0.0
Boys_backup                     0         0.0
Facilities                      0         0.0
Girls_main                      0         0.0
Girls_backup                    0         0.0
Lecture                         0         0.0
Library                         0         0.0
Mess                            0         0.0
date                            0         0.0
year                            0         0.0
month                           0         0.0
day                             0         0.0
hour                            0         0.0
ALLSKY_SFC_SW_DWN               0         0.0
WS2M                            0         0.0
PRECTOTCORR                     0         0.0

In [48]:
df.to_csv(
    r"C:\Users\User\OneDrive\Documents\IoT-Based-Intelligent-Building-DSS\data\processed\integrated_building_dataset.csv",
    index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.